name: Main Workflow
on:
  pull_request:
    branches: [main, next-minor]
  push:
    branches: [main]
jobs:
  build:
    name: Actions
    strategy:
      matrix:
        node-version: [16, 17]
    runs-on: ubuntu-latest
    container: node:${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          id: cache-dependencies
          node-version: 16
          cache: 'npm'
          cache-dependency-path: |
            **/package-lock.json
            ./package-lock.json
      - uses: actions/cache@v3
        with:
          id: cache-packages
          path: packages/**
          key: ${{ runner.os }}-${{ hashFiles('packages/*/package') }}
      - run: node --version
      - run: npm i
      - run: npm run format
      - run: npm run lint
      - run: npm run package
      - run: npm run test
